title: PM in the Loop
description: >
  A Workplace Fiction on Product Management in the Age of AI<br><br>
  <strong>Authors:</strong><br>
  <a href="https://www.linkedin.com/in/smanas/">Manas Sharma</a><br>
  <a href="https://www.linkedin.com/in/siddharthsaoji/">Siddharth Saoji</a><br>
  <a href="https://www.linkedin.com/in/sanskriti-uma/">Sanskriti Uma</a>
theme: jekyll-theme-hacker
markdown: kramdown
show_downloads: false

