title: PM in the Loop
description: A Workplace Fiction on Product Management in the Age of AI, By Sanskriti Uma - https://www.linkedin.com/in/sanskriti-uma/, Manas Sharma - https://www.linkedin.com/in/smanas/, and Siddharth Saoji - https://www.linkedin.com/in/siddharthsaoji/
theme: jekyll-theme-hacker
markdown: kramdown
show_downloads: false

